{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0fcface0-a37f-40fd-b207-05761d9d8897",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trades columns: ['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side', 'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL', 'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID', 'Timestamp']\n",
      "FearGreed columns: ['timestamp', 'value', 'classification', 'date']\n",
      "\n",
      "Trades sample:\n",
      "                                       Account  Coin  Execution Price  \\\n",
      "0  0xae5eacaf9c6b9111fd53034a602c192a04e082ed  @107           7.9769   \n",
      "1  0xae5eacaf9c6b9111fd53034a602c192a04e082ed  @107           7.9800   \n",
      "\n",
      "   Size Tokens  Size USD Side     Timestamp IST  Start Position Direction  \\\n",
      "0       986.87   7872.16  BUY  02-12-2024 22:50        0.000000       Buy   \n",
      "1        16.00    127.68  BUY  02-12-2024 22:50      986.524596       Buy   \n",
      "\n",
      "   Closed PnL                                   Transaction Hash     Order ID  \\\n",
      "0         0.0  0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630   \n",
      "1         0.0  0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630   \n",
      "\n",
      "   Crossed       Fee      Trade ID     Timestamp  \n",
      "0     True  0.345404  8.950000e+14  1.730000e+12  \n",
      "1     True  0.005600  4.430000e+14  1.730000e+12  \n",
      "\n",
      "FearGreed sample:\n",
      "     timestamp  value classification        date\n",
      "0  1517463000     30           Fear  01-02-2018\n",
      "1  1517549400     15   Extreme Fear  02-02-2018\n",
      "Using time column: 'Timestamp'\n",
      "Using FG date column: 'date'\n",
      "Trades date range: 2023-03-28 to 2025-06-15\n",
      "FG date range: 2018-01-02 to 2025-12-04\n",
      "Using PnL column: 'Closed PnL'\n",
      "Merged shape: (14103, 22)\n",
      "\n",
      "PnL by Sentiment:\n",
      "                    mean  count       std\n",
      "Classification                          \n",
      "Extreme Greed   22.2297   7141  633.7048\n",
      "Fear            25.4188   6962  306.1669\n",
      "\n",
      "PnL-Sentiment Correlation: -0.0032\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Load data\n",
    "trades_df = pd.read_csv(r\"C:\\Users\\SHUBHAM\\Downloads\\hyperliquid_trades.csv\")\n",
    "fg_df = pd.read_csv(r\"C:\\Users\\SHUBHAM\\Downloads\\fear_greed.csv\")\n",
    "\n",
    "print(\"Trades columns:\", trades_df.columns.tolist())\n",
    "print(\"FearGreed columns:\", fg_df.columns.tolist())\n",
    "print(\"\\nTrades sample:\\n\", trades_df.head(2))\n",
    "print(\"\\nFearGreed sample:\\n\", fg_df.head(2))\n",
    "\n",
    "# Auto-detect time/date columns for trades\n",
    "time_cols = ['time', 'timestamp', 'Time', 'Timestamp']\n",
    "date_col_fg = ['Date', 'date', 'timestamp', 'Timestamp']\n",
    "\n",
    "time_col = next((col for col in time_cols if col in trades_df.columns), None)\n",
    "if time_col is None:\n",
    "    print(\"No time column found! Available:\", trades_df.select_dtypes(include=['datetime64', 'int64', 'float64']).columns.tolist())\n",
    "    raise KeyError(\"Add time column manually or check CSV\")\n",
    "\n",
    "print(f\"Using time column: '{time_col}'\")\n",
    "\n",
    "# Preprocess trades time\n",
    "if trades_df[time_col].dtype in ['int64', 'float64']:\n",
    "    trades_df['time'] = pd.to_datetime(trades_df[time_col], unit='ms', errors='coerce')\n",
    "else:\n",
    "    trades_df['time'] = pd.to_datetime(trades_df[time_col], errors='coerce')\n",
    "trades_df['date'] = trades_df['time'].dt.date\n",
    "\n",
    "# Auto-detect FG date column\n",
    "fg_date_col = next((col for col in date_col_fg if col in fg_df.columns), None)\n",
    "if fg_date_col is None:\n",
    "    raise KeyError(\"No date column in FearGreed CSV\")\n",
    "print(f\"Using FG date column: '{fg_date_col}'\")\n",
    "\n",
    "fg_df['date'] = pd.to_datetime(fg_df[fg_date_col], errors='coerce').dt.date\n",
    "\n",
    "# Ensure Classification exists (common names: Classification, value_classification, fear_greed_category)\n",
    "class_cols = ['Classification', 'classification', 'fear_greed_category', 'FEAR_GREED_CATEGORY']\n",
    "class_col = next((col for col in class_cols if col in fg_df.columns), None)\n",
    "if class_col:\n",
    "    fg_df['Classification'] = fg_df[class_col].astype(str)\n",
    "else:\n",
    "    print(\"No classification column; using numeric if available.\")\n",
    "    fg_df['Classification'] = pd.cut(fg_df[fg_date_col].astype(float), bins=[0,25,50,75,100], \n",
    "                                     labels=['Extreme Fear', 'Fear', 'Greed', 'Extreme Greed'])\n",
    "\n",
    "# Drop invalids\n",
    "trades_df = trades_df.dropna(subset=['date'])\n",
    "fg_df = fg_df.dropna(subset=['date'])\n",
    "\n",
    "print(\"Trades date range:\", trades_df['date'].min(), \"to\", trades_df['date'].max())\n",
    "print(\"FG date range:\", fg_df['date'].min(), \"to\", fg_df['date'].max())\n",
    "\n",
    "# Merge (ensure 'closedPnL' exists; alt: 'pnl', 'PnL')\n",
    "pnl_col = next((col for col in trades_df.columns if 'pnl' in col.lower() or 'pnl' in col.lower()), 'closedPnL')\n",
    "print(f\"Using PnL column: '{pnl_col}'\")\n",
    "\n",
    "merged = pd.merge(trades_df, fg_df, on='date', how='inner')\n",
    "print(f\"Merged shape: {merged.shape}\")\n",
    "\n",
    "if merged.empty:\n",
    "    print(\"No overlaps. Try weekly merge:\")\n",
    "    trades_df['week'] = trades_df['time'].dt.isocalendar().week\n",
    "    fg_df['week'] = fg_df['date'].dt.isocalendar().week\n",
    "    merged = pd.merge(trades_df, fg_df, on='week', how='inner')\n",
    "    print(f\"Weekly merged shape: {merged.shape}\")\n",
    "else:\n",
    "    # Analysis\n",
    "    pnl_by_sentiment = merged.groupby('Classification')[pnl_col].agg(['mean', 'count', 'std']).round(4)\n",
    "    print(\"\\nPnL by Sentiment:\\n\", pnl_by_sentiment)\n",
    "    \n",
    "    # Correlation\n",
    "    sentiment_num = merged['Classification'].map({'Fear':0, 'Extreme Fear':0, 'Greed':1, 'Extreme Greed':1}).fillna(0.5)\n",
    "    corr = sentiment_num.corr(merged[pnl_col].fillna(0))\n",
    "    print(f\"\\nPnL-Sentiment Correlation: {corr:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "909c88f5-800b-4654-9855-2a2c8e7da0db",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
